version: '3.8'

services:
  repomap:
    build: .
    volumes:
      - ./projects:/projects
      - ./cache:/app/cache
    environment:
      - PYTHONPATH=/app
      - CACHE_DIR=/app/cache
    command: ["/projects/my-project", "--map-tokens", "2048", "--verbose"]
    # Uncomment the line below to run interactively
    # stdin_open: true
    # tty: true
