version: '3.8'

services:
  repomap:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    volumes:
      - ./projects:/projects
      - ./cache:/app/cache
    environment:
      - PYTHONPATH=/app
      - CACHE_DIR=/app/cache
    command: ["analyze", "/projects/test-project", "--verbose"]
    # Uncomment the line below to run interactively
    # stdin_open: true
    # tty: true
